services: 
   # API Gateway
  api-gateway-svc:
    image: 'yarp-api-gateway:localhost'
    build: 
      context: ./API-Collection
      dockerfile: YARP-Gateway/Dockerfile
    depends_on:
      - users-api-svc
      - products-api-svc
      - reports-api-svc
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Serilog__WriteTo__0__Args__serverUrl=${SEQ_SERVER_URL}
      - Kestrel__Certificates__Default__Password=password
      - Kestrel__Certificates__Default__Path=/app/Certificate/localhost.pfx
      - EnforceHttpsRedirection=true
      - ReverseProxy__Clusters__users-api-cluster__Destinations__destination1__Address=${USERS_API_URL} 
      - ReverseProxy__Clusters__products-api-cluster__Destinations__destination1__Address=${PRODUCTS_API_URL}
      - ReverseProxy__Clusters__reports-api-cluster__Destinations__destination1__Address=${REPORTS_API_URL}
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Yarp=Debug
      - Logging__LogLevel__Microsoft.AspNetCore=Debug
      - IdentityServerConfiguration__IdentityUrl=${IDENTITY_API_URL}
    ports:
      - 10080:10080
      - 10443:10443
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https
    networks:
      - proxybackend

  # IdentityServer-API
  identity-api-svc:
    image: 'yarp-identity-api:localhost'
    build: 
      context: ./API-Collection
      dockerfile: IdentityProvider-API/Dockerfile
    depends_on:
      - postgres
      - seq
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - EFConfiguration__ConnectionString=${POSTGRES_CONNECTION_STRING}
      - Serilog__WriteTo__0__Args__serverUrl=${SEQ_SERVER_URL}
      - Kestrel__Certificates__Default__Password=password
      - Kestrel__Certificates__Default__Path=/app/Certificate/localhost.pfx
      - EnforceHttpsRedirection=true
      - DockerizedUrl=
    ports:
      - 9080:9080
      - 9443:9443
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https
    networks:
      - proxybackend

  # Users-API
  users-api-svc:
    image: 'yarp-users-api:localhost'
    build: 
      context: ./API-Collection
      dockerfile: Users-API/Dockerfile
    depends_on:
      - postgres
      - seq
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - EFConfiguration__ConnectionString=${POSTGRES_CONNECTION_STRING}
      - Serilog__WriteTo__0__Args__serverUrl=${SEQ_SERVER_URL}
      - Kestrel__Certificates__Default__Password=password
      - Kestrel__Certificates__Default__Path=/app/Certificate/localhost.pfx
      - EnforceHttpsRedirection=true
    ports:
      - 5080:5080
      - 5443:5443
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https
    networks:
      - proxybackend

  # Products-API
  products-api-svc:
    image: 'yarp-products-api:localhost'
    build: 
      context: ./API-Collection
      dockerfile: Products-API/Dockerfile
    depends_on:
      - postgres
      - seq
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - EFConfiguration__ConnectionString=${POSTGRES_CONNECTION_STRING}
      - Serilog__WriteTo__0__Args__serverUrl=${SEQ_SERVER_URL}
      - Kestrel__Certificates__Default__Password=password
      - Kestrel__Certificates__Default__Path=/app/Certificate/localhost.pfx
      - EnforceHttpsRedirection=true
    ports:
      - 6080:6080
      - 6443:6443
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https
    networks:
      - proxybackend

  # Reports-API
  reports-api-svc:
    image: 'yarp-reports-api:localhost'
    build: 
      context: ./API-Collection
      dockerfile: Reports-API/Dockerfile
    depends_on:
      - postgres
      - seq
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - EFConfiguration__ConnectionString=${POSTGRES_CONNECTION_STRING}
      - Serilog__WriteTo__0__Args__serverUrl=${SEQ_SERVER_URL}
      - Kestrel__Certificates__Default__Password=password
      - Kestrel__Certificates__Default__Path=/app/Certificate/localhost.pfx
      - EnforceHttpsRedirection=true
    ports:
      - 7080:7080
      - 7443:7443
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https
    networks:
      - proxybackend

  # Postgres
  postgres:
    container_name: yarp-container-pg
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - app-postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - proxybackend

  # PgAdmin Web UI
  pgadmin:
    container_name: yarp-container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    restart: unless-stopped
    networks:
      - proxybackend

  # Datalust Seq
  seq:
    container_name: yarp-container-seq
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8081:80"
    networks:
      - proxybackend

networks:
  proxybackend:
    name: proxybackend
    driver: bridge

volumes:
  app-postgres-data:
